name: Frontend CI

on:
  push:
    tags:
      - "v*"

env:
  # 你的 ACR 实例域名（不带协议）
  ACR_REGISTRY: crpi-ywue2o6mpn8qaq0l.cn-hangzhou.personal.cr.aliyuncs.com

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4            # 升级到新版 action

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Login to Alibaba Cloud ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}   # = 彭德文
          password: ${{ secrets.ACR_PASSWORD }}   # = J3nyiJaRdSxec9iG

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend/
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_NAME=bisheng-frontend
            APP_VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: |
            ${{ env.ACR_REGISTRY }}/tangshu/bisheng-frontend:latest
            ${{ env.ACR_REGISTRY }}/tangshu/bisheng-frontend:${{ steps.get_version.outputs.VERSION }}